//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub mod prelude;

pub mod wb_comment;
pub mod wb_feed;
pub mod wb_follower;
pub mod wb_like;
pub mod wb_post;
pub mod wb_user;
pub mod wb_user_info;
