//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::wb_comment::Entity as WbComment;
pub use super::wb_feed::Entity as WbFeed;
pub use super::wb_follower::Entity as WbFollower;
pub use super::wb_like::Entity as WbLike;
pub use super::wb_post::Entity as WbPost;
pub use super::wb_user::Entity as WbUser;
pub use super::wb_user_info::Entity as WbUserInfo;
